### ISSUE TITLE
Make grid classes mixins

### ISSUE THREAD

**Issue by stouset** [anjlab/bootstrap-rails#1]
Is there any chance you'll turn the `span#{n}` and `row` classes into mixins, so we can use semantic classes instead of layout-based ones in our views?

**Comment by gavinhughes** [comment]
+1  I'll probably get busy on this in next the next few days.  If you want to take a stab at it maybe this can serve as a guide http://github.com/gavinhughes/semantic_grid

**Comment by yury** [comment]
@stouset, sorry for the late response.

you can include _columns_ mixin instead.

```
.some_meaning_name {
  @include columns(4)
}
```

**Comment by stouset** [comment]
Oh. Is this (reasonably) new, or am I just crazy? I don't remember the `span#{n}`s being generated through the mixing when I looked.

Thanks.
