### ISSUE TITLE
css files not included in application.css

### ISSUE THREAD

**Issue by qichunren** [anjlab/bootstrap-rails#12]
I followed README to add

```
    *= require bootstrap
```

to app/assets/stylesheets/application.css,then rails s to run app, view html source, found bootstrap css not included in application.css.

I found in http://localhost:3000/assets/application.css?body=1 file, there is :

<pre>
/*
 * This is a manifest file that'll automatically include all the stylesheets available in this directory
 * and any sub-directories. You're free to add application-wide styles to this file and they'll appear at
 * the top of the compiled file, but it's generally better to create a new file per style scope.
*/

*= require bootstrap
</pre>

**Comment by mike-park** [comment]
I think your require needs to be part of the first comment.

/*
- This is a manifest file that'll automatically include all the stylesheets available in this directory
- and any sub-directories. You're free to add application-wide styles to this file and they'll appear at
- the top of the compiled file, but it's generally better to create a new file per style scope.
  *
  *= require bootstrap
  */

**Comment by qichunren** [comment]
very nice.Thank you.
