### ISSUE TITLE
Using mixins

### ISSUE THREAD

**Issue by Nerian** [anjlab/bootstrap-rails#16]
Hi,

Thank for your gem, really great job :clap:

I want to add a translucid border to `.well`.  According to the docs (http://twitter.github.com/bootstrap/less.html) I need to do something like this:

```
.well{
    .#translucent > .border();
}
```

But it clearly is not the way since it gives me the error:  `Invalid CSS after "...ucent > .border": expected "{", was "();"`

I put that code at the end of  `assets/stylesheet/bootstrap.css.scss`

How can I use mixins?

Thanks

**Comment by yury** [comment]
```
.well {
   @include  translucent-border;
}
```

**Comment by Nerian** [comment]
Thanks!
