### ISSUE TITLE
File to import not found or unreadable: bootstrap.

### ISSUE THREAD

**Issue by antonversal** [anjlab/bootstrap-rails#19]
I follow readme:
Add necessary stylesheet file to app/assets/stylesheets/application.css

``` css
*= require bootstrap
*= require responsive
```

It's ok
But when i try:

You can override bootstrap variables:
1. replace `*= require bootstrap` with `*= require app_bootstrap`
2. create `app_bootstrap.css.scss` :

``` scss
// change colors
$linkColor: red;

// change grid
$gridColumnWidth: 70px;
$gridGutterWidth: 10px;

// import original bootstrap
@import "bootstrap";
@import "responsive";
```

I get this error:

``` error
File to import not found or unreadable: bootstrap.
Load path: /Users/antonversal/rorprojects/onboard
  (in /Users/antonversal/rorprojects/onboard/app/assets/stylesheets/app_bootstrap.css.scss)
```

Rails 3.2.1

**Comment by yury** [comment]
Can you gist your Gemfile.lock?

**Comment by jb-san** [comment]
having the exact same issue, heres mine https://gist.github.com/1940074

**Comment by yury** [comment]
@jb-san and Gemfile please.

**Comment by jb-san** [comment]
my gemfile https://gist.github.com/1940218

**Comment by jb-san** [comment]
I just tried it in a rails s server instead of pow, and it works

**Comment by yury** [comment]
still can't reproduce %(

Also need application.css and app_bootstrap.css.scss.
Many thanks for help.

**Comment by jb-san** [comment]
yeah I just restarted my pow, and now it works just fine, something about pow :)

**Comment by yury** [comment]
@jb-san thanks a lot.
