### ISSUE TITLE
Javascript not working

### ISSUE THREAD

**Issue by gavinhughes** [anjlab/bootstrap-rails#2]
I'm on the current master branch I can't get the javascript to work.  For testing I've got js slimmed down to this:

``````
```<script src="/assets/jquery.js?body=1" type="text/javascript"></script>
<script src="/assets/bootstrap-dropdown.js?body=1" type="text/javascript"></script>
<script src="/assets/application.js?body=1" type="text/javascript"></script>```
``````

If I click on a dropdown, it doesn't respond to the click event.  However, if I remove bootstrap-dropdown, and just add this:

`$ ->
  $('.dropdown').click ->
    $(@).addClass('open')`

it responds just fine.  It's not just the dropdown js either, none of the bootstrap js files work.

Any ideas?

**Comment by davidsulc** [comment]
Hi, make sure you're adding the required attributes to the elements you want ot use js with  (e.g. data-dropdown for dropdowns, per http://twitter.github.com/bootstrap/javascript.html#dropdown).

**Comment by gavinhughes** [comment]
Working now.  Thanks.
