### ISSUE TITLE
Mixin grid-core-span is missing argument $gridColumnWidth.

### ISSUE THREAD

**Issue by bluebu** [anjlab/bootstrap-rails#24]
After updated rails to 3.2.8,  it reported  "Mixin grid-core-span is missing argument $gridColumnWidth."

Maybe it should be the sass issue , I found the sass gem has updated from 3.1.20 to 3.2.0

When I set the sass version to 3.1.20, it's ok.

But in 3.2.0, the 165 line code in the file "navbar.scss"  can't be compressed sucessfully.

and the code is below:

.navbar-fixed-bottom .container {
  @include grid-core-span($gridColumns);   // here is the code
}

**Comment by yury** [comment]
Released anjlab-bootstrap-rails v2.0.4.4  with fix.

Thanks for report.

**Comment by sudhirj** [comment]
Superb responsiveness - thanks a ton for the quick fix.

**Comment by bluebu** [comment]
so quick! thx a lot ^_^

**Comment by zjhui** [comment]
I have `Rails 3.2.13` and  `* sass (3.2.8)   * sass-rails (3.2.6)`, `* anjlab-bootstrap-rails (2.3.1.1 c778407)`, It comes the same error: `Mixin grid-core-span is missing argument $gridColumnWidth.
  (in /home/zjhui/.rvm/gems/ruby-2.0.0-p0/gems/anjlab-bootstrap-rails-2.0.3.2/vendor/assets/stylesheets/bootstrap.scss)` . It may come the bug again?

**Comment by zjhui** [comment]
I followed this [page](https://github.com/anjlab/bootstrap-rails/commit/8cf830a0a739d00aae2a46771ffc2a3eee40bde8), manually add this code  `@include grid-core-span($gridColumns, $gridColumnWidth, $gridGutterWidth);`, than it seems work.

**Comment by yury** [comment]
@zjhui that is strange. Can you point exactly line on github that you changed?

**Comment by zjhui** [comment]
It's so stange. My gemfile is: `gem 'anjlab-bootstrap-rails', :require => 'bootstrap-rails',
                                :git => 'git://github.com/anjlab/bootstrap-rails.git'`  
and the `navbar.scss` path on my computer is `/home/zjhui/.rvm/gems/ruby-2.0.0-p0/gems/anjlab-bootstrap-rails-2.0.3.2/vendor/assets/stylesheets/navbar.scss`, however on github the path is: `vendor/twitter/scss/navbar.scss` and the line _199_ on github , the code was `.navbar-fixed-bottom .container {
  @include grid-core-span($gridColumns, $gridColumnWidth, $gridGutterWidth);
}`. But the computer on my computer is: `.navbar-fixed-bottom .container {                                                                                                                      @include grid-core-span($gridColumns);`

**Comment by yury** [comment]
This is strange:
/home/zjhui/.rvm/gems/ruby-2.0.0-p0/gems/anjlab-bootstrap-rails-2.0.3.2

Your app is using 2.0.3.2 version on your gems.

Try to `bundle update anjlab-bootstrap-rails`
and run you app with bundle exec.

Also, can you show your Gemfile.lock?

**Comment by zjhui** [comment]
Follow your step, it works. And here is my `grep -C 5 bootsrap Gemfile.lock`: 

```
    GIT
  remote: git://github.com/anjlab/bootstrap-rails.git
  revision: c77840781930eae034d5dbfeb372446e93765bc2
  specs:
    anjlab-bootstrap-rails (2.3.1.1)
      railties (>= 3.0)
      sass (>= 3.2)

GEM
  remote: http://ruby.taobao.org/
--
      activesupport (= 3.2.13)
    activesupport (3.2.13)
      i18n (= 0.6.1)
      multi_json (~> 1.0)
    arel (3.0.2)
    bootstrap-will_paginate (0.0.3)
      will_paginate
    bootstrap_helper (1.4.1)
      railties (~> 3.0)
      thor (~> 0.14)
    builder (3.0.4)
    capybara (2.1.0)
      mime-types (>= 1.16)
--

PLATFORMS
  ruby

DEPENDENCIES
  anjlab-bootstrap-rails!
  bootstrap-will_paginate (= 0.0.3)
  bootstrap_helper (= 1.4.1)
  capybara
  coffee-rails (~> 3.2.1)
  factory_girl_rails
  guard-rspec
  jquery-rails
```

P.S: i change the `navbar.scss` back and run `rails s` without `bundle exec`, it works too.

**Comment by yury** [comment]
cool

## 

Yury Korolev
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
