### ISSUE TITLE
newest 2.1 update gives error

### ISSUE THREAD

**Issue by magicmarkker** [anjlab/bootstrap-rails#27]
/home/bem/.rvm/gems/ree-1.8.7-2011.03/gems/anjlab-bootstrap-rails-2.1.0.3/lib/bootstrap-rails/engine.rb:4: 
syntax error, unexpected ':', expecting kEND initializer 'anjlab-bootstrap-rails-setup', group: :all do |app| ^ /home/bem/.rvm/gems/ree-1.8.7-2011.03/gems/anjlab-bootstrap-rails-2.1.0.3/lib/bootstrap-rails/engine.rb:11: 
syntax error, unexpected kEND, expecting $end

**Comment by magicmarkker** [comment]
I see it's because you're using the ruby 1.9.x syntax on "group: :all"

**Comment by yury** [comment]
I'm sorry for that. Fixed in new version.
