### ISSUE TITLE
bootstrap-responsive ... "error compiling css asset"

### ISSUE THREAD

**Issue by teambonzai** [anjlab/bootstrap-rails#28]
when bootstrap-responsive is included n the application.css, the site displays something similar to:

error compiling css asset

sass::syntaxerror: invalid css after "...ia (max-width: ": expected expression (e.g. 1px, bold), was "$navbarcollapse..." (/location/bootstrap-responsive.scss)

(/location/responsive-navbar.scss:8)

it might not be exact since i couldn't copy the error text directly.  gem 'anjlab-bootstrap-rails', '>= 2.1', :require => 'bootstrap-rails' is installed.  there is no error when  i remove "*= require twitter/bootstrap-responsive" from application.css.  let me know if you need more details.  the site is using rails 3.2.3.

**Comment by yury** [comment]
This is error in readme. 

if you want use responsive, you should import 'twitter/bootstrap' and 'twitter/bootstrap-responsive' via `@import`

```
@import "twitter/bootstrap";
@import "twitter/bootstrap-responsive";
```

in your `applications.css.scss`

**Comment by teambonzai** [comment]
thanks.  i changed the code to match your suggestion.

however, it is still displaying the same error as above when the responsive styles are imported. i'll troubleshoot some more. it seems to have an issue with "max-width: $navbarCollapseWidth".

**Comment by yury** [comment]
This is strange. I have working bootstrap-responsive on heroku. And it is working fine.

Can you gist your Gemfile and Gemfile.lock?

**Comment by yury** [comment]
I think you need update sass gem. What version do you have?

**Comment by teambonzai** [comment]
here are the gemfiles: https://gist.github.com/c4ee645dcf8db5eb0628  

thanks for the help

**Comment by yury** [comment]
I believe that sass version >= 3.2 is required, so I released new version with that dependency.

Please try new version.

**Comment by teambonzai** [comment]
great.  that fixed it.  thanks again!

**Comment by yury** [comment]
Welcome. Thanks for bug report.
