### ISSUE TITLE
image path is wrong in v 2.1.1.0

### ISSUE THREAD

**Issue by tsechingho** [anjlab/bootstrap-rails#29]
in https://github.com/anjlab/bootstrap-rails/blob/master/vendor/frameworks/twitter/bootstrap/variables.scss

it should be:

$iconSpritePath:          image-path("twitter/glyphicons-halflings.png") !default;
$iconWhiteSpritePath:     image-path("twitter/glyphicons-halflings-white.png") !default;

**Comment by yury** [comment]
thanks
