### ISSUE TITLE
typeahead

### ISSUE THREAD

**Issue by magicmarkker** [anjlab/bootstrap-rails#30]
Hi, I was wondering if anyone has had trouble with the typeahead not selecting the item in the dropdown when you click on it?

**Comment by yury** [comment]
Just tested - everything is Ok.

**Comment by magicmarkker** [comment]
Actually, sorry, it works fine in Firefox, but not chrome. Here's an example in chrome: http://screencast.com/t/akPuuMZJKUmf

**Comment by yury** [comment]
Hmm. Tested in Safari Version 6.0 (8536.25, 537+) , Firefox (15.0.1), and Chrome (Version 23.0.1255.0 dev)

**Comment by magicmarkker** [comment]
Chrome(Version 21.0.1180.89) was the video above, looks like its a twitter bug, not your gem. Sorry about that, you can close this if you'd like
