### ISSUE TITLE
No support for "input-block-level" class

### ISSUE THREAD

**Issue by bedaro** [anjlab/bootstrap-rails#37]
(see http://twitter.github.com/bootstrap/base-css.html#forms)

The input-block-level class was added around version 2.3.0, but it does not appear in the stylesheets that are part of this gem.

I just confirmed that 2.3.1 downloaded from the Bootstrap site does include the style definition.

**Comment by yury** [comment]
Thanks for report. Please try new version.

**Comment by bedaro** [comment]
Thanks, that fixed it!
