### ISSUE TITLE
Problems running on Heroku

### ISSUE THREAD

**Issue by kjakm** [anjlab/bootstrap-rails#44]
I've been using bootstrap-rails fine locally. I just uploaded my project to Heroku but what I run db:migrate on the server I get the following error:

```
uninitialized constant Bootstrap::Rails::Engine::Sass
/app/vendor/bundle/ruby/2.0.0/bundler/gems/bootstrap-rails-7556d2c17115/lib/bootstrap-rails/engine.rb:6:in `block in <class:Engine>'
```

**Comment by yury** [comment]
You have to move sass and bootstrap-rails from development group to top level in your Gemfile.

**Comment by kjakm** [comment]
I have sass-rails in my assets group. 

```
gem 'anjlab-bootstrap-rails', :require => 'bootstrap-rails',
                              :github => 'anjlab/bootstrap-rails',
                              :branch => '3.0.0'
```

is top level.

**Comment by yury** [comment]
You need to move sass-rails to top level too

**Comment by kjakm** [comment]
Thanks that solved it.

**Comment by yury** [comment]
Also you can try to put both to assets groups.

**Comment by kjakm** [comment]
I'm using Rails 4 and read that the assets group has been removed so I've moved everything out into the top level. Thanks for your help and work on the gem!
