### ISSUE TITLE
Rails 4 uninitialized constant Bootstrap::Rails::Engine::Sass (NameError)

### ISSUE THREAD

**Issue by randomor** [anjlab/bootstrap-rails#47]
``` ruby
lib/bootstrap-rails/engine.rb:6:in `block in <class:Engine>': uninitialized constant Bootstrap::Rails::Engine::Sass (NameError)
```

I was going to try this, but it looks like it doesn't work for rails4. Or am I missing something? I do have Sass gem installed. Thanks.

**Comment by yury** [comment]
we are using this gem in 3 rails 4 projects and 3 rails 3 projects without problems :)

Can you gist your Gemfile and Gemfile.lock?

**Comment by randomor** [comment]
My coworker put the sass gem into an asset gem group, which is not used in rails4. That was causing the problem. :) Thanks!
