### ISSUE TITLE
Add missing holder.js

### ISSUE THREAD

**Issue by caike** [anjlab/bootstrap-rails#48]
Add missing holder.js library that is used to display thumbnail images

**Comment by rmoriz** [comment]
Do we really need holder.js? it's just used in the bootstrap docs to create example images. Also it requires special attribution when included…

**Comment by yury** [comment]
@rmoriz,  I think, it's good for prototyping. In production you should specify only js files that you need.

**Comment by rmoriz** [comment]
@yury why make the default for prototyping, not for production? And because documentation is missing, i bet that 99% of the users will not discover this upfront and violate the holder.js attribution license…

**Comment by caike** [comment]
Good point about the licensing. Maybe submit a pull request to add that to the README ?
I'd imagine most people that use bootstrap use it mostly for prototyping, so I think including holder.js makes sense.

**Comment by yury** [comment]
I removed holder.js from bootstrap.js for now

**Comment by Entamut** [comment]
Dummy image generator seems to be a good alternative (i.e. http://fpoimg.com/). No need for additional JavaScript.
Only inconvenient is no support for offline image generation (like holder.js was providing). Anyway you can always add holder.js on your own. No need to be included in bootstrap :)
