### ISSUE TITLE
Issue with gradients in IE

### ISSUE THREAD

**Issue by davidsulc** [anjlab/bootstrap-rails#5]
Hi,

There seems to be an issue with gradients in IE 9 (and lower versions, most likely).

It seems like the `DXImageTransform.Microsoft.gradient` function calls in `mixins.scss` get passed 3-digit color codes that aren't processed properly. For example, #333 renders as #000333. At least, that's what the issue seems to be. I've tried fixing this, but unfortunately I've had no luck...

**Comment by yury** [comment]
There is no simple solution here
SASS doesn't support expanding to [IE hex string](https://github.com/nex3/sass/issues/4)
Compass has it's own [implementation](https://github.com/chriseppstein/compass/blob/stable/lib/compass/sass_extensions/functions/colors.rb#L37)

Still thinking about it...

**Comment by davidsulc** [comment]
I tried something similar: https://github.com/davidsulc/bootstrap-rails/commit/87e5ac99eb3dc76e8c81e3675c5ea17faab5871e

I tried earlier with adding the alpha channel, but it made no difference. I'll give it another try...

(I'll rename the function to `ie_hex_str` it makes much more sense...)

**Comment by davidsulc** [comment]
Fixed in pull request (https://github.com/anjlab/bootstrap-rails/pull/7). Turns out my solution wasn't far off...

**Comment by yury** [comment]
@davidsulc, I released new version with the fix.
Thanks a lot!
