### ISSUE TITLE
Feature request - non-fluid design

### ISSUE THREAD

**Issue by bvalerius** [anjlab/bootstrap-rails#50]
I'd love to see a branch or option when installing this gem to get a version with all of the responsive or fluid-design styles stripped out. I'm looking to use Bootstrap 3 with sass and rails, but I really want a static non-responsive grid. Not sure if this is something anyone else is interested in, but I feel like it would be.

**Comment by frabrunelle** [comment]
Check out http://getbootstrap.com/examples/non-responsive/.

**Comment by nickserv** [comment]
This is related to Bootstrap 3, not this repository. Bootstrap 3 disables non-fluid designs by default, and this repository would not be able to fix that as long as you need Bootstrap 3.

That being said, @frabrunelle linked to a very helpful example on how to use non-fluid designs in Bootstrap 3, and there's [more useful information in the Bootstrap 3 docs](http://getbootstrap.com/getting-started/#disable-responsive).
