### ISSUE TITLE
Inputs & dropdowns broken somehow

### ISSUE THREAD

**Issue by tzoro** [anjlab/bootstrap-rails#52]
I'm on anjlab-bootstrap-rails (3.0.0.rc1 377c7ee) and all inputs and drop-downs are broken for me. Did bundle clean all-ready, even tried manually remove gem from system and installed it again but same thing happen again.

In application.css.scss i have only  *= require twitter/bootstrap.

Everything else, grid, text styles, etc looks fine.. No idea why. Thanks !

**Comment by yury** [comment]
can you gist your form html?

**Comment by tzoro** [comment]
i will tonight...

**Comment by DevanB** [comment]
It seems my dropdowns are not working as well.

**Comment by yury** [comment]
Please help me to reproduce problem.

Can you gist final html for your drop downs?

Also, please update to latest git version and rm -rf tmp/cache

**Comment by DevanB** [comment]
Yury,

Here is a gist of my application.html.erb and application.css.scss (https://gist.github.com/DevanB/6204991). I am creating a navbar that has a settings menu that is a dropdown when the user is signed in. I believe I have changed all of the syntax to the new BS3 syntax for dropdown menus. I am not calling any specific javascript other than including the twitter/bootstrap.

Is the 3.0.0 branch the latest? I'm calling it in my Gemfile via:

gem 'anjlab-bootstrap-rails', :require => 'bootstrap-rails',
                                :github => 'anjlab/bootstrap-rails',
                                :branch => '3.0.0'

**Comment by yury** [comment]
Do you have '//= require twitter/bootstrap' in your application.js?

this is mine

``` javascript
//= require jquery
//= require jquery_ujs
//= require twitter/bootstrap
//= require_tree .
```

@DevanB your example works ok.
Off topic: I advise you to look at [slim](http://slim-lang.com) all views become clean and compact.

**Comment by DevanB** [comment]
Interesting.

I moved my //= require twitter/bootstrap from:

//= require twitter/bootstrap
//= require jquery
//= require jquery_ujs
//= require retina
//= require rails.validations
//= require rails.validations.simple_form
//= require anjlab/datepicker
//= require anjlab/timepicker
//= require_tree .

to:

//= require jquery
//= require jquery_ujs
//= require retina
//= require rails.validations
//= require rails.validations.simple_form
//= require twitter/bootstrap
//= require anjlab/datepicker
//= require anjlab/timepicker
//= require_tree .

And now, no more problems.

Off topic again: Would you choose slim over HAML? I haven't looked into either, just curious.

**Comment by yury** [comment]
Sure, bootstrap js depends on jquery. 

Slim vs Haml... I prefer slim, it is less symbolic for me.

**Comment by DevanB** [comment]
9107777011?

I will look into it then! Thanks for all the help again Yury! Keep up the awesome work!

**Comment by yury** [comment]
This is iPhone autocomplete ;( sorry

**Comment by yury** [comment]
Close for now, reopen if needed

**Comment by tzoro** [comment]
Hi all, sorry for such delay... i was on road trip - no pc /no code.
Here is gist of my navbar: https://gist.github.com/tzoro/6260437

Just now i did update and my navbar disappeared :) I see markup in inspector but navbar don't want to show. I tried to remove this classes from markup "nav-collapse collapse navbar-responsive-collapse" and navbar shoved somehow. Hope this helps, regards !

**Comment by yury** [comment]
@tzoro here fixed gist https://gist.github.com/yury/6270212
