### ISSUE TITLE
Including using instructions doesn't find "twttier/bootstrap" - Rails 4, Bootstrap 3

### ISSUE THREAD

**Issue by toobulkeh** [anjlab/bootstrap-rails#53]
Following the instructions on the README doesn't include twitter bootstrap properly... heading back to the twitter-bootstrap-rails gem

**Comment by devdavidkarlsson** [comment]
bump

**Comment by yury** [comment]
Look at read.me now

**Comment by toobulkeh** [comment]
I went ahead with https://github.com/thomas-mcdonald/bootstrap-sass gem yesterday on their 3 branch. Sorry!

**Comment by yury** [comment]
@toobulkeh no problem. Happy coding.
