### ISSUE TITLE
Any way to set BS version?

### ISSUE THREAD

**Issue by kbrowneatx** [anjlab/bootstrap-rails#54]
Hi, all. I am working on a simple app to learn more RoR. It's Rails 4 + Simple_form and Cocoon gems to handle a nested model/form requirement. Running into issues with Bootstrap 3.0.0rc1 breaking Simple_form, so I was hoping to back up to BS 2.3.2. Since I'm loading BS through this gem, I can only set the version of bootstrap-rails through the gemfile. Is there a way to tell the gem to load 2.3.2 rather than 3.0.0? (Did not see a config/initializer...)

**Comment by yury** [comment]
You can fix anjlab-bootstrap-rails version on your Gemfile

`gem 'anjlab-bootstrap-rails', '2.3.1.2'`

**Comment by kbrowneatx** [comment]
Gah - I figured that out and forgot to update. Very much appreciate the reply, Yury, and your work to build this gem!
