### ISSUE TITLE
Not running on Heroku

### ISSUE THREAD

**Issue by rafrafgit** [anjlab/bootstrap-rails#55]
I get the following error when you update my build (rails 3.2) on heroku

/app/vendor/bundle/ruby/2.0.0/bundler/gems/bootstrap-rails-507323616c5a/lib/bootstrap-rails/engine.rb:6:in `block in class:Engine': uninitialized constant Bootstrap::Rails::Engine::Sass (NameError)

please help :/

**Comment by rafrafgit** [comment]
I should add that it works fine locally on my machine.

**Comment by yury** [comment]
https://github.com/anjlab/bootstrap-rails/issues/44

What section are you using for bootstrap-rails? it should be in same section as Sass gem

**Comment by rafrafgit** [comment]
Thanks for the quick answer. 
Im using gem 'sass-rails',   '~> 3.2.3'

Do I need to specify bootstrap-rails in my gem file?

**Comment by rafrafgit** [comment]
Here is the gemfile

source 'https://rubygems.org'

gem 'rails', '3.2.13'
gem 'anjlab-bootstrap-rails', :require => 'bootstrap-rails',
                              :github => 'anjlab/bootstrap-rails',
                              :branch => '3.0.0'
gem 'bcrypt-ruby', '3.0.1'
gem 'letsrate'
gem "paperclip", "~> 3.0"
gem 'aws-sdk'
gem 'acts_as_commentable', '3.0.1'
gem 'rails_autolink'

group :development, :test do
  gem 'sqlite3', '1.3.5'
  gem 'rspec-rails', '2.11.0'
end

# Gems used only for assets and not required

# in production environments by default.

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '3.2.2'
  gem 'uglifier', '1.2.3'
end

gem 'jquery-rails'

group :test do
  gem 'capybara', '1.1.2'
end

group :production do
  gem 'pg', '0.12.2'
end

**Comment by yury** [comment]
ok, just move everything out from :assets group.

**Comment by rafrafgit** [comment]
thanks, that did the trick :)
