### ISSUE TITLE
Loading Bootstrap RC1

### ISSUE THREAD

**Issue by davidedicillo** [anjlab/bootstrap-rails#56]
Is there a way to load RC1 instead of RC2 until the CSS are updated. The update is breaking some stuff so I need to temporary roll back to RC1 until I'm done fixing them.

**Comment by yury** [comment]
you can specify ref: '05c1923ce02c9d6c9320745c608476b62e437d96' in your gem file. (Remember to `rm tmp/cache` after bundle install)
