### ISSUE TITLE
Glyphicons on Heroku

### ISSUE THREAD

**Issue by frabrunelle** [anjlab/bootstrap-rails#58]
In development, the glyphicons work fine, but not in production on Heroku.

The errors I get look like that:
`ActionController::RoutingError (No route matches [GET] "/assets/twitter/glyphicons-halflings-regular.ttf")`

**Comment by yury** [comment]
Sorry for that, with v3.0.0.0.1 it should be ok.

Reopen if needed

**Comment by frabrunelle** [comment]
Thank you!!! It works :smile:
