### ISSUE TITLE
Style not running on heroku

### ISSUE THREAD

**Issue by tjy86** [anjlab/bootstrap-rails#60]
Style shows locally:

http://biandang.herokuapp.com/

Gemfile:
source 'https://rubygems.org'
ruby '2.0.0'
gem 'rails', '4.0.0'
gem 'pg', '0.15.1'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'anjlab-bootstrap-rails', :require => 'bootstrap-rails',
                              :github => 'anjlab/bootstrap-rails',
                              :branch => '3.0.0'
gem 'figaro'
gem 'high_voltage'
gem 'simple_form', '>= 3.0.0.rc'
gem 'slim'
gem 'thin'
group :development do
  gem 'better_errors'
  gem 'binding_of_caller', :platforms=>[:mri_19, :rbx]
  gem 'guard-bundler'
  gem 'guard-rails'
  gem 'haml-rails'
  gem 'haml2slim'
  gem 'html2haml'
  gem 'hub', :require=>nil
  gem 'quiet_assets'
  gem 'rb-fchange', :require=>false
  gem 'rb-fsevent', :require=>false
  gem 'rb-inotify', :require=>false
end

**Comment by nickserv** [comment]
This is probably an issue with Rails and/or Heroku, not this repository. I remember having very similar issues before with Rails 4 on Heroku, but without using this repository.

You are most likely running into one of these two problems:
1. You forgot to add additional dependencies for Rails 4 on Heroku (like the `rails_12factor` gem, which you don't seem to be using).
2. The asset pipeline settings for your app cause asset precompiling to either fail or not happen when you deploy to Heroku. This would probably be an issue with your config files in `config`.

Please see these two articles on the Heroku Dev Center:
- [Getting Started with Rails 4.x on Heroku](https://devcenter.heroku.com/articles/rails4-getting-started)
- [Rails Asset Pipeline on Heroku Cedar](https://devcenter.heroku.com/articles/rails-asset-pipeline)

**Comment by tjy86** [comment]
installed with 12factor gem. works now! cheers

**Comment by nickserv** [comment]
Ah awesome, I didn't expect it to be that easy. :+1: Glad I could help.
