### ISSUE TITLE
problem with .navbar-nav margin

### ISSUE THREAD

**Issue by frabrunelle** [anjlab/bootstrap-rails#61]
Here's is how my navbar looks like when collapsed. the margin of .navbar-nav is -7.5px
![screen shot 2013-08-20 at 2 01 47 pm](https://f.cloud.github.com/assets/1114844/995710/10cf09b0-09c3-11e3-885f-fc2e75c2264d.png)

But on the official Bootstrap site, the margin of .navbar-nav is 7.5px -15px when collapsed. So if I change it with Dev Tools here's how the navbar looks.
![screen shot 2013-08-20 at 2 04 52 pm](https://f.cloud.github.com/assets/1114844/995711/17950be6-09c3-11e3-8568-a2e923a1ef7a.png)

I looked into the source code but I couldn't find the problem.

**Comment by yury** [comment]
should be ok in v3.0.0.2

**Comment by frabrunelle** [comment]
Awesome, the margin of .navbar-nav is now correct!
