### ISSUE TITLE
Undefined mixin 'btn-pseudo-states'.

### ISSUE THREAD

**Issue by DevanB** [anjlab/bootstrap-rails#62]
when deploying to my server, I am getting an error of "Undefined mixin 'btn-pseudo-states'." I'm calling anjlab-bootstrap-rails, :require => 'bootstrap-rails, :github => 'anjlab/bootstrap-rails' in the assets group of my gemfile.

**Comment by DevanB** [comment]
I've tracked this down and believe the problem is being thrown because of the datepicker.css.scss in anjlab-widgets-1.0.10

**Comment by yury** [comment]
Yep, anjlab-widgets was outdated. Please try latest version.

Thank you.
