### ISSUE TITLE
Problem with navbar - collapse not displaying on >= 768px

### ISSUE THREAD

**Issue by gitjul** [anjlab/bootstrap-rails#64]
Navbar is not displaying in it's normal form (not collapsed, that is). When I look into the source, there's a general .collapse { display: none } declaration in _component-animations.scss that is overriding it's normal behaviour.

For now I repeated this bit of Bootstrap styling in my stylesheet, which temporarily fixes the problem:

``` sass
@media screen and (min-width: 768px)
  .collapse
    display: block !important
```

**Comment by yury** [comment]
Can't reproduce :( 

Can you gist your page html?

Thank you.

**Comment by gitjul** [comment]
Shit, I think I know what I did wrong, I just found this in the Bootstrap blog: ".nav-collapse has been renamed to .navbar-collapse". I'm very sorry for the mixup, I feel stupid. My bad, please close issue.

**Comment by yury** [comment]
No problem
