### ISSUE TITLE
Releasing as a gem

### ISSUE THREAD

**Issue by lassebunk** [anjlab/bootstrap-rails#73]
Hi. Thanks for making this gem. It works great.

I was wondering if you could release it as a gem on RubyGems.org so we don't have to rely on this repository being available.

Thanks.

**Comment by yury** [comment]
It is released as a gem.

`gem 'anjlab-bootstrap-rails', '>= 3.0.0.0', :require => 'bootstrap-rails'`

**Comment by lassebunk** [comment]
Ok. The readme just says

```
gem 'anjlab-bootstrap-rails', :require => 'bootstrap-rails',
                              :github => 'anjlab/bootstrap-rails'
```

Thanks.
