### ISSUE TITLE
Input fields don't have rounded corners

### ISSUE THREAD

**Issue by JustusLauten** [anjlab/bootstrap-rails#75]
I have version 3.0.0.2 of the gem installed and when I use simple input fields (e.g. %input{type:"text", placeholder:"Type something…"} ) the corners are not rounded. Somehow my input class is not extended by the form-control class.

I also restarted the server after installation and did "rm -rf tmp/cache"

I require the bootstrap style as follows in my application.css.scss:
 *= require jquery.ui.all
 *= require twitter/bootstrap
 *= require_self
 *= require "custom"
...

**Comment by mmahalwy** [comment]
The way I got it fixed is to include the class "form-control"

To fix it for the time being, you will have to manually mimic bootstrap's docs to the rails as opposed to previously when it all worked like magic with bootstrap 2.

Also, I'd advise to just make your own tags:

def my_text_field_tag(name, value)
      text_field_tag(name, value, class: "form-control")
end

**Comment by jrhorn424** [comment]
:+1:  for custom tags.
