### ISSUE TITLE
Don't load FONTS!

### ISSUE THREAD

**Issue by duhanov** [anjlab/bootstrap-rails#78]
No load Fonts in Production mode:
http://www.webpagescreenshot.info/img/523c8c22a776e1-82770086

Development OK:
http://www.webpagescreenshot.info/img/523c8c75261c24-28243292

**Comment by duhanov** [comment]
Inside /assets/bootstrap-d32340e9fd08e187f9e9643687cea3b6.css: 
http://www.webpagescreenshot.info/img/523c8d8b263551-55982279

But, 
http://theseus.1mm.com.ua/assets/twitter/glyphicons-halflings-regular-8230cc7eedc7cac3101ae208bf7d33a5.eot - file not found.

**Comment by yury** [comment]
ok, can you show your nginx config?

it seems, that nginx is not configured to serve fonts properly.

**Comment by duhanov** [comment]
Tnx! Im edited conf file. 

```
    server {
            server_name xxxxxxx.com.ua;
            listen 5.9.78.174;
            set $root_path /var/www/maximus/data/www/xxxxxxx.com.ua/current/public;

            root /var/www/maximus/data/www/xxxxxxx.com.ua/current/public;
            location ~* ^.+\.(eot|svg|woff|ttf|jpg|jpeg|gif|png|svg|js|css|mp3|ogg|mpe?g|avi|zip|gz|bz2?|rar|swf)$ {
```

add eot|svg|woff|ttf| 

-ALL WORK!
