### ISSUE TITLE
Correct shadow/border on forms

### ISSUE THREAD

**Issue by mmahalwy** [anjlab/bootstrap-rails#81]
I am still not getting the correct correct look for the form inputs as on the bootstrap documentation. 
Also, form horizontal does not work properly.

**Comment by mmahalwy** [comment]
The way I got it fixed is to include the class "form-control"

To fix it for the time being, you will have to manually mimic bootstrap's docs to the rails as opposed to previously when it all worked like magic with bootstrap 2.

Also, I'd advise to just make your own tags:

def my_text_field_tag(name, value)
text_field_tag(name, value, class: "form-control")
end

**Comment by yury** [comment]
Yep, this is how new BS add styles to controls.
