### ISSUE TITLE
Change readme for application.css

### ISSUE THREAD

**Issue by 14113** [anjlab/bootstrap-rails#84]
It's not necessarily to add 'import' into application.css. 
We can use 'require'. It's faster and better for developing

**Comment by tough-griff** [comment]
Using the sprockets `//= require` directive is only advisable if you want to use Bootstrap without any sort of customization or overrides.

From http://guides.rubyonrails.org/asset_pipeline.html:

> If you want to use multiple Sass files, you should generally use the Sass @import rule instead of these Sprockets directives. Using Sprockets directives all Sass files exist within their own scope, making variables or mixins only available within the document they were defined in.

So, I would disagree that `//= require` is "faster and better for developing" in all cases.

**Comment by yury** [comment]
I totally agree with @tough-griff

**Comment by yury** [comment]
Closing this for now
