### ISSUE TITLE
Table Contextual classes doesn't generate

### ISSUE THREAD

**Issue by wildjcrt** [anjlab/bootstrap-rails#90]
https://github.com/anjlab/bootstrap-rails/blob/master/app/assets/stylesheets/twitter/bootstrap/_tables.scss#L171-L173

I'm not sure what happened but those lines don't generate in css…

`gem 'anjlab-bootstrap-rails', '~> 3.0.2.0', :require => 'bootstrap-rails'`

I have tried `bundle install` but fail.

Rails: 4.0.1

**Comment by yury** [comment]
stop server, rm -rf tmp/cache and try again.

**Comment by wildjcrt** [comment]
@yury thanks! I forget the cache files.
